---

- name: install homebrew via the curl oneliner
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: update and upgrade homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: install homebrew cask
  homebrew: name=caskroom/cask/brew-cask state=latest

- name: install homebrew services
  homebrew_tap: tap=homebrew/services state=present
